"""initial_schema

Revision ID: adbdffe6c3a2
Revises: 
Create Date: 2026-06-12 18:34:20.084991

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'adbdffe6c3a2'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
